services:
  nginx:
    image: nginx:stable-alpine-slim
    container_name: miniApps
    ports:
      - 4444:80
    volumes:
      # TODO: ふざけたファイル名を維持しつつスマートにマウントしたい・・・
      - ../単品で機能するhtml/クラウド管理できない環境でアカウント情報など一覧表示するやつ.html:/var/www/account/index.html
      - ../単品で機能するhtml/クラウド管理できない環境でアカウント情報など一覧表示するやつ.json:/var/www/account/クラウド管理できない環境でアカウント情報など一覧表示するやつ.json
      - ../単品で機能するhtml/書式は全て殺す.html:/var/www/style_slayer/index.html
      - ../単品で機能するhtml/え、薬飲んだっけ？飲んだらポチッと記録しとこ！.html:/var/www/medicine_management/index.html
      - ../単品で機能するhtml/火継.html:/var/www/fire_keeper/index.html
      - ./scripts/index.html:/var/www/index.html
      - ./.nginx/:/etc/nginx/conf.d/
